### ISSUE TITLE
Icon file format

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [peppelg/TDeskMulti#1]
I noticed your code had commented out code for the Icon file.  You need to pass in an .ICO file for tkinter to use when setting the window icon.  A PNG file won't work, as you found out.

**Comment by peppelg** [comment]
fixed, but it doesn't work on linux 
![image](https://user-images.githubusercontent.com/29309124/50660295-92e1d080-0f9f-11e9-9569-2ebb67447e0d.png)

**Comment by MikeTheWatchGuy** [comment]
You **sure** it's finding the icon file?

**Comment by peppelg** [comment]
Yes, on Windows it's working

**Comment by peppelg** [comment]
If I import PySimpleGuiQt it works
![image](https://user-images.githubusercontent.com/29309124/50663621-9038a880-0faa-11e9-80f5-98e91ff17f9b.png)

**Comment by MikeTheWatchGuy** [comment]
Completely different programs PySimpleGUI and PySimpleGUIQt.  It's nice that they're source code compatible.

Do you get an error on Linux?  What's the filename and where is it located?

**Comment by MikeTheWatchGuy** [comment]
Do other programs on your Linux machine have icons there?

I don't see icons in the upper left on my linux system.  I do see the icon correctly set in the taskbar.
![image](https://user-images.githubusercontent.com/13696193/50667545-cb75b000-0f87-11e9-9661-06a3cd51ccc2.png)

**Comment by peppelg** [comment]
> Completely different programs PySimpleGUI and PySimpleGUIQt. It's nice that they're source code compatible.
> 
> Do you get an error on Linux? What's the filename and where is it located?

Zero errors. Filename is icon.ico and it's located in /home/giuseppe/Git/TDeskMulti/icon.ico

**Comment by peppelg** [comment]
> Do other programs on your Linux machine have icons there?
> 
> I don't see icons in the upper left on my linux system. I do see the icon correctly set in the taskbar.
> ![image](https://user-images.githubusercontent.com/13696193/50667545-cb75b000-0f87-11e9-9661-06a3cd51ccc2.png)

![image](https://user-images.githubusercontent.com/29309124/50684169-df1b2800-1014-11e9-80ed-5f9c7cc7dd7d.png)

**Comment by peppelg** [comment]
![image](https://user-images.githubusercontent.com/29309124/50685196-88175200-1018-11e9-82e7-0d3e3d0c26fa.png)
base64 gif icon is working

**Comment by peppelg** [comment]
![image](https://user-images.githubusercontent.com/29309124/50685585-0fb19080-101a-11e9-997a-86bea3663978.png)
in this way it works,,.,

**Comment by MikeTheWatchGuy** [comment]
Oh, right, GIF.

I changed the icon format in the main file to be GIF.  There was an error reported when I used PNG.  Plus, GIF is recognized by the 2.7 version of tkinter.
